### ISSUE TITLE
Ajustar css e html da tela de login

### ISSUE THREAD

**Issue by DEXTERNATAN** [DEXTERNATAN/VemComigo#14]

**Comment by augustoalmeida** [comment]
@DEXTERNATAN 
Enviei as modificações na branch https://github.com/DEXTERNATAN/VemComigo/tree/login-ajustes

**Comment by DEXTERNATAN** [comment]
@augustoalmeida Feito subi o codigo e fiz o merge. Vou fechar a issue.
